AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
  TargetRubyVersion: 2.6
Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false