AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
  TargetRubyVersion: 2.6
Metrics/LineLength:
  Enabled: true
  Max: 100

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false